server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto=update:
  jackson:
    time-zone: Asia/Shanghai
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/person?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Jinli03
    hikari:
      maximum-pool-size: 10  # 配置连接池的最大连接数
      minimum-idle: 5  # 配置连接池的最小空闲连接数
      idle-timeout: 30000  # 配置连接池连接的空闲超时时间，单位：毫秒

      # 开启事务管理
      transaction:
        management:
          enabled: true  # 确保启用事务管理
          pool-name: HikariCP

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true